// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetUserByName.sql

package database

import (
	"context"
)

const getUserByName = `-- name: GetUserByName :one
SELECT name FROM users
WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	err := row.Scan(&name)
	return name, err
}
