// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: listfeed.sql

package database

import (
	"context"
)

const listfeeds = `-- name: Listfeeds :many
SELECT feed.name,feed.url,COALESCE(users.name, '') AS user_name
FROM feed
LEFT JOIN users ON feed.user_id = users.id
`

type ListfeedsRow struct {
	Name     string
	Url      string
	UserName string
}

func (q *Queries) Listfeeds(ctx context.Context) ([]ListfeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, listfeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListfeedsRow
	for rows.Next() {
		var i ListfeedsRow
		if err := rows.Scan(&i.Name, &i.Url, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
